### PR TITLE
`SpacyModelManager` refactor

### PR DESCRIPTION
**Pull request by lkeegan**
- refactor `SpacyModel` and `ModelManager` into `SpacyModelManager`
- `SpacyModelManager` features
  - create a spacy model from a supplied base config - generates a default config if not provided by user
  - train & evaluate the model using data from a `DataManager`
  - display test string
  - edit metadata
  - publish to huggingface
- model_manager_test notebook -> DemoNotebook_spacy_model
- remove spacy model training code from `DataManager`
- spacy_model.py -> spacy_data_handler.py

### CODE REVIEW

**Comment by GwydionJon** [comment]
The `spacy_huggingface_hub` package is not included in the `environment.yml` or the ` requirements.txt`. 

And maybe check if the metadata has been set before publication is allowed?

Otherwise its looks good to me.

**Review by GwydionJon — COMMENTED** [review]
The `spacy_huggingface_hub` package is not included in the `environment.yml` or the ` requirements.txt`. 

And maybe check if the metadata has been set before publication is allowed?

Otherwise its looks good to me.

**Comment by lkeegan** [comment]
@GwydionJon thanks for the feedback, done in: https://github.com/ssciwr/moralization/pull/68/commits/35465e51ea7bf77bb515674c649daee3f157881d  and https://github.com/ssciwr/moralization/pull/68/commits/17ad13962baba9652729b39335d2705c9f23a359

**Review by iulusoy — COMMENTED** [review]
lgtm

**Pull request merged**
